### ISSUE TITLE
missing block graph?

### ISSUE THREAD

**Issue by aniquetahir** [ViDA-NYU/data-polygamy#1]
Hi,
I noticed an error while running the code with my own data set:
File does not exist: /block-graph

I think there should be a file for block-graph.txt in the data/ folder but its missing?

**Comment by fchirigati** [comment]
Hi @aniquetahir ,

Thanks for letting me know. I updated the code recently to support blocks as a spatial resolution, but forgot to add the appropriate files. It should work now. If it doesn't work for this or another reason, please feel free to create more issues.

Best,
Fernando.
