### ISSUE TITLE
Code of thresholds

### ISSUE THREAD

**Issue by mengjiang1994** [ViDA-NYU/data-polygamy#2]
Hi there,
I'm looking for the code of automatically computing thresholds since I'm confused with the result I generated from the framework:

For example, I have generated the relationship of <dataset A, attr A, avg> with <dataset B, attr A, avg>, <dataset B, attr B, avg>, <dataset B, attr C, avg> .  Below is a simple example of it

```
first scalar function,  second scalar function
avg-AA, avg-BA, ...
avg-AA, avg-BB, ...
avg-AA, avg-BC, ...
```

In this scenario, the first scalar function is the scalar function of dataset A. In my opinion, the _number of negative events on the first scalar function only_ and the _number of positive events on the first scalar function only_ should keep the same value in both of AA-BA, AA-BB, AA-BC. Which should look like this:

```
first scalar function,  second scalar function, ..., #sf1pstv, #sf1ngtv, #sf2pstv, #sf2ngtv, ...
avg-AA, avg-BA, ..., 0, 4, 1, 9, ...
avg-AA, avg-BB, ..., 0, 4, 9, 25, ...
avg-AA, avg-BC, ..., 0, 4, 2, 1, ...
```

However, in my result, the #sf1pstv, #sf1ngtv, are different in every line:
```
first scalar function,  second scalar function, ..., #sf1pstv, #sf1ngtv, #sf2pstv, #sf2ngtv, ...
avg-AA, avg-BA, ..., 0, 4, 1, 9, ...
avg-AA, avg-BB, ..., 2, 3, 9, 25, ...
avg-AA, avg-BC, ..., 4, 5, 2, 1, ...
```

I've already done my best to review the paper, the slides in AWS re:Invent 2016 and the code, but I cannot find where talk about it. can you give me some tips?

**Comment by fchirigati** [comment]
Hi @mengjiang1994 

_number of negative events on the first scalar function only_ does **not** correspond to the total number of negative events of that scalar function. Given a relationship between attributes A1 (first scalar function) and A2 (second scalar function), _number of negative events on the first scalar function only_ means the number of intersections (in space and time) between A1 and A2 where A1 is a negative feature, and A2 is not a feature. Therefore, while the feature computation is independent of the relationship, the intersections will definitely change for every relationship.

The code for computing the thresholds is in this [method](https://github.com/ViDA-NYU/data-polygamy/blob/master/data-polygamy/src/main/java/edu/nyu/vida/data_polygamy/ctdata/TopologicalIndex.java#L238). The kmeans for the persistence points is computed [here](https://github.com/ViDA-NYU/data-polygamy/blob/master/data-polygamy/src/main/java/edu/nyu/vida/data_polygamy/ctdata/TopologicalIndex.java#L496).

Let me know if you have any further questions.

**Comment by mengjiang1994** [comment]
Hi **@fchirigati** 

It makes sense to me.

Cheers : )
